/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PFloatLabel: typeof import('primevue/floatlabel')['default']
    PForm: typeof import('@primevue/forms/form')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMessage: typeof import('primevue/message')['default']
    PToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
